### ISSUE TITLE
Crash Android androiddelay: -1 AND transition other than slide

### ISSUE THREAD

**Issue by Stylemayster** [shprink/ionic-native-transitions#12]
The application crash when androiddelay is set to -1 and we attempt to make a transition other than "slide". In my case it was fade, mut I've tried flip and it crash too.

Here is the copy-paste from logcat:
10-19 16:19:11.293  22071-22071/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.compagny.test, PID: 22071
    java.lang.IllegalArgumentException: delay < 0: -1
            at java.util.Timer.schedule(Timer.java:454)
            at com.telerik.plugins.nativepagetransitions.NativePageTransitions.doFadeTransition(NativePageTransitions.java:312)
            at com.telerik.plugins.nativepagetransitions.NativePageTransitions.access$1700(NativePageTransitions.java:27)
            at com.telerik.plugins.nativepagetransitions.NativePageTransitions$3.run(NativePageTransitions.java:275)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

It only append with delay to -1. At 0 or > it doesn't crash.

Have a nice day!
:)

**Comment by shprink** [comment]
Are you using telerik's plugin v0.4.3 ?

**Comment by shprink** [comment]
Because -1 was introduced in that version

**Comment by Stylemayster** [comment]
Yes it's 0.4.3

**Comment by Stylemayster** [comment]
Another info, it work well on iPad. But it seem to have a little flash when slide left with delay set to -1. slide right (when you go back) seem to be ok.

**Comment by shprink** [comment]
Thanks for sharing all of this.

**Comment by shprink** [comment]
@NgYueHong check this out  https://github.com/Telerik-Verified-Plugins/NativePageTransitions/issues/78

**Comment by shprink** [comment]
Guys beta6 is out, it is base on Telerik's plugin 0.5 which allow -1 for all transitions on Android and iOS. Do you mind testing on your devices?

**Comment by shprink** [comment]
All fixed in 0.5.4
