### ISSUE TITLE
Exception when returning from phonegap-plugin-barcodescanner

### ISSUE THREAD

**Issue by felixwahner** [shprink/ionic-native-transitions#82]
When returning from a "camera view / barcodescanner" an exception is thrown and the devices view freezes.
The app still responds to touch events (seen in the inspector) but the view on the device doesn't get updated.  

This happens even if $ionicNativeTransitions is deactivated before switching the state.

This is the exception that gets thrown:
``` 
I/art     (19748): WaitForGcToComplete blocked for 7.470ms for cause HeapTrim
I/Camera2Client( 2980): disconnect(), Camera 0, calling PID: 19748, client PID: 19748, service PID: 2980
I/Camera2ClientBase( 2980): Closed Camera 0. Client was: de.xxx.app.yyy (PID 19748, UID 10100)
I/chromium(19748): [INFO:CONSOLE(15488)] "[native transition] enabling plugin", source: file:///android_asset/www/index.js?6ccf0f925323bc1ba577 (15488)
I/chromium(19748): [INFO:CONSOLE(15488)] "[native transition] disabling ionic transitions", source: file:///android_asset/www/index.js?6ccf0f925323bc1ba577 (15488)
I/chromium(19748): [INFO:CONSOLE(15488)] "[native transition] $stateChangeStart", source: file:///android_asset/www/index.js?6ccf0f925323bc1ba577 (15488)
I/chromium(19748): [INFO:CONSOLE(15488)] "[native transition]", source: file:///android_asset/www/index.js?6ccf0f925323bc1ba577 (15488)
E/AndroidRuntime(19748): FATAL EXCEPTION: main
E/AndroidRuntime(19748): Process: de.xxx.app.yyy, PID: 19748
E/AndroidRuntime(19748): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
E/AndroidRuntime(19748):     at com.telerik.plugins.nativepagetransitions.NativePageTransitions$1.run(NativePageTransitions.java:151)
E/AndroidRuntime(19748):     at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(19748):     at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(19748):     at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(19748):     at android.app.ActivityThread.main(ActivityThread.java:5538)
E/AndroidRuntime(19748):     at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19748):     at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(19748):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:958)
E/AndroidRuntime(19748):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:753)
I/Process (19748): Sending signal. PID: 19748 SIG: 9
I/HwSystemManager( 3402): HoldService:uid:10100 pid:19748 died
I/HwSystemManager( 3402): HoldService:oldVersionKey:10100,19748
I/MediaProcessHandler( 3231): processOp opType: 1, uid: 10100, pid: 19748
W/MediaProcessHandler( 3231): remove target not exist, maybe the UI process: uid: 10100, pid: 19748
```

**Comment by shprink** [comment]
I think that more of a Java problem. Can you create a ticket over there? https://github.com/Telerik-Verified-Plugins/NativePageTransitions
